### ISSUE TITLE
[REJECTED] Add CSS to bookmarklet

### ISSUE THREAD

**Issue by sergeevabc** [h5o/h5o-bookmarklet#6]
TOC must have specified background and links color, otherwise it looks unreadable on some pages.

Edit: when TOC is big, scrollbar is missing, should be fixed as well.

**Comment by dominykas** [comment]
PR welcome.

**Comment by sergeevabc** [comment]
Had user been able to polish reported roughness, he would be called a developer.
The latter role is yours, hence the badge, yet passion to carry on seems to be lost.
Consider [marking project as abandoned][2] to strangle public expectations of improvements at birth.

Edit: frustrated users alike could switch to [Marc Hoyois’ fork][1].

[1]: https://hoyois.github.io/
[2]: https://github.com/h5o/h5o-bookmarklet/blob/master/README.md

**Comment by dominykas** [comment]
I don't owe you anything.

**Comment by sergeevabc** [comment]
Public issue tracker implies developer’s attitude to gather feedback and fulfill public expectations.
Want to share with no further responsibility? State it honestly [in the first place][1] and mute the feedback.

[1]: https://github.com/h5o/h5o-bookmarklet/blob/master/README.md

**Comment by dominykas** [comment]
Thank you for your feedback. It was taken into consideration. I will definitely address it at the earliest of my convenience.
